import React, { useState } from 'react';
import { 
  FileText, 
  Sparkles, 
  AlertCircle, 
  CheckCircle2, 
  Building2, 
  Cpu, 
  Layers 
} from 'lucide-react';
import { useIndustrialApp } from '../../context/IndustrialAppContext';
import { ReportType, ReportModel } from '../../types/industrial';
import { Modal } from '../common/Modal';

interface GenerateReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  onReportGenerated?: (report: ReportModel) => void;
}

export const GenerateReportModal: React.FC<GenerateReportModalProps> = ({
  isOpen,
  onClose,
  onReportGenerated
}) => {
  const { 
    plants, 
    machines, 
    selectedPlantId, 
    selectedMachineId, 
    generateReport, 
    activeInvestigation,
    currentUser 
  } = useIndustrialApp();

  const [reportType, setReportType] = useState<ReportType>('incident-investigation');
  const [targetMachineId, setTargetMachineId] = useState<string>(selectedMachineId || 'C-204');
  const [reportTitle, setReportTitle] = useState<string>('Incident Investigation: Compressor C-204 Vibration Excursion');
  const [notes, setNotes] = useState<string>('High-frequency telemetry revealed fluid film collapse on tilt-pad bearing caused by heat exchanger cooling water silt restriction.');
  const [isGenerating, setIsGenerating] = useState(false);
  const [validationError, setValidationError] = useState<string | null>(null);

  const targetMachine = machines.find(m => m.id === targetMachineId) || machines[0];

  const handleTypeChange = (type: ReportType) => {
    setReportType(type);
    if (type === 'incident-investigation') {
      setReportTitle(`Incident Investigation: ${targetMachine?.name || 'Compressor C-204'} Vibration Excursion`);
    } else if (type === 'machine-health') {
      setReportTitle(`Comprehensive Asset Health Audit: ${targetMachine?.name || 'Equipment Unit'}`);
    } else if (type === 'maintenance-summary') {
      setReportTitle(`Preventive Turnaround & Reliability Summary: ${targetMachine?.tag || 'Asset'}`);
    } else if (type === 'plant-performance') {
      setReportTitle(`Facility Reliability & OEE Dossier: ${plants.find(p => p.id === selectedPlantId)?.name || 'Plant'}`);
    } else {
      setReportTitle(`Executive Operations Reliability Briefing`);
    }
  };

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    setValidationError(null);

    if (!reportTitle.trim()) {
      setValidationError('Report Title is required.');
      return;
    }

    setIsGenerating(true);

    try {
      const generated = await generateReport({
        type: reportType,
        name: reportTitle.trim(),
        machineId: targetMachine?.id,
        machineOrPlant: `${targetMachine?.name} (${targetMachine?.tag})`,
        summary: notes.trim() || 'Comprehensive multi-sensor audit dossier generated by INDUSTRIX AI neural telemetry engine.',
        sections: {
          incidentSummary: notes.trim(),
          timeline: [
            { time: '06:40:02 UTC', event: 'Primary cooling water differential pressure spiked across lube heat exchanger HEX-204.', severity: 'warning' },
            { time: '06:42:15 UTC', event: 'Drive-end radial vibration exceeded ISO 10816 Zone B threshold (5.76 mm/s RMS).', severity: 'critical' },
            { time: '06:44:00 UTC', event: 'Anti-surge bypass valve modulated by DCS to prevent full aerodynamic surge trip.', severity: 'warning' },
            { time: '06:50:30 UTC', event: 'Operator throttled compression train throughput by 8% to restore hydrodynamic wedge.', severity: 'info' }
          ],
          sensorEvidence: [
            { parameter: 'Radial Vibration Velocity', value: `${targetMachine?.metrics.vibrationRMS.toFixed(2)} mm/s RMS`, baseline: '4.50 mm/s', deviation: '+28.0%', severity: 'Critical' },
            { parameter: 'Drive-End Bearing Metal Temp', value: `${targetMachine?.metrics.bearingTemp.toFixed(1)}°C`, baseline: '72.0°C', deviation: '+14.0%', severity: 'Warning' },
            { parameter: 'Lube Header Pressure', value: '2.94 bar', baseline: '3.20 bar', deviation: '-8.1%', severity: 'Warning' }
          ],
          detectedCorrelations: [
            { pair: 'Lube Pressure ↔ Vibration Velocity', coefficient: -0.89, interpretation: 'Strong inverse correlation. Fluid film thinning directly triggers sub-synchronous rotor whirl.' },
            { pair: 'Cooling Delta-P ↔ Bearing Temperature', coefficient: 0.94, interpretation: 'High direct correlation. Heat exchanger restriction causes immediate thermal ramp in babbitt lining.' }
          ],
          potentialCauses: [
            { rank: 1, cause: 'Cooling water filter silt accumulation and solenoid actuator failure', probability: 0.94, notes: 'Direct mechanical cause confirmed by differential pressure sensors.' },
            { rank: 2, cause: 'Coupling Angular Misalignment', probability: 0.14, notes: 'Disproven by 2X axial vibration phase analysis.' }
          ],
          aiAnalysis: 'Physics-informed neural models diagnosed oil whirl instability on Drive-End Tilt Pad bearing #2. Fluid film wedge thickness was restored after the 8% throughput throttling command was dispatched.',
          recommendedActions: [
            { priority: 'P1', action: 'Replace backwash filter pneumatic actuator on F-102', owner: 'J. De Vries (Mechanical)', deadline: '2026-09-22' },
            { priority: 'P2', action: 'Inspect and flush HEX-204 shell & tube bundle with descaler', owner: 'M. Bakker (Turnaround)', deadline: '2026-09-23' },
            { priority: 'P3', action: 'Lock PM schedule integrity in SAP PM', owner: 'Operations Director', deadline: '2026-09-25' }
          ],
          investigationConclusion: `Investigation conclusion for ${targetMachine?.tag}: Fluid-film collapse was arrested prior to babbitt metal wiping. Compliance confirmed under API 670, ISO 14224, and IEC 62443. Audit sign-off certified by Lead Reliability Director.`
        }
      });

      setIsGenerating(false);
      onClose();
      if (onReportGenerated) onReportGenerated(generated);
    } catch (err: any) {
      setIsGenerating(false);
      setValidationError(err?.message || 'Failed to generate report.');
    }
  };

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title="Generate Industrial Intelligence Dossier"
      subtitle="ISO 14224 & API 670 Standardized Reporting Workflow"
      icon={FileText}
      maxWidth="2xl"
      footer={
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 rounded-lg border border-zinc-700 bg-zinc-800 hover:bg-zinc-700 text-zinc-300 text-xs font-mono-tech transition-colors"
          >
            Cancel
          </button>
          <button
            type="button"
            onClick={handleGenerate}
            disabled={isGenerating}
            className="px-4 py-2 rounded-lg bg-emerald-500 hover:bg-emerald-400 text-zinc-950 font-mono-tech text-xs font-bold flex items-center gap-1.5 transition-colors disabled:opacity-50"
          >
            {isGenerating ? (
              <>
                <span className="w-3.5 h-3.5 border-2 border-zinc-950 border-t-transparent rounded-full animate-spin" />
                <span>Compiling Dossier...</span>
              </>
            ) : (
              <>
                <Sparkles className="w-3.5 h-3.5" />
                <span>Compile & Sign Dossier</span>
              </>
            )}
          </button>
        </div>
      }
    >
      <form onSubmit={handleGenerate} className="space-y-5">
        {validationError && (
          <div className="p-3 rounded-lg bg-rose-500/10 border border-rose-500/30 text-rose-300 text-xs flex items-center gap-2">
            <AlertCircle className="w-4 h-4 shrink-0" />
            <span>{validationError}</span>
          </div>
        )}

        {/* Report Classification Grid */}
        <div>
          <label className="block text-xs font-mono-tech text-zinc-400 uppercase tracking-wider mb-2">
            1. Select Report Classification
          </label>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
            {[
              { type: 'incident-investigation' as ReportType, title: 'Incident Investigation', desc: 'Full 7-step RCA, five-whys & CAPA' },
              { type: 'machine-health' as ReportType, title: 'Machine Health Audit', desc: 'RUL telemetry, vibration FFT & bearing wear' },
              { type: 'maintenance-summary' as ReportType, title: 'Maintenance Summary', desc: 'Turnaround history, parts replaced & SAP PM' },
              { type: 'plant-performance' as ReportType, title: 'Plant Performance', desc: 'Facility OEE, active load & fleet availability' },
              { type: 'energy-analysis' as ReportType, title: 'Energy Analysis', desc: 'Specific power consumption & kilowatt efficiency' },
              { type: 'executive-operations' as ReportType, title: 'Executive Briefing', desc: 'High-level reliability & downtime risk exposure' }
            ].map(item => (
              <button
                key={item.type}
                type="button"
                onClick={() => handleTypeChange(item.type)}
                className={`p-3 rounded-xl border text-left transition-all ${
                  reportType === item.type
                    ? 'border-emerald-500 bg-emerald-950/20 text-white'
                    : 'border-zinc-800 bg-zinc-950/40 text-zinc-400 hover:border-zinc-700'
                }`}
              >
                <div className="font-mono-tech text-xs font-bold text-white mb-0.5">
                  {item.title}
                </div>
                <div className="text-[11px] text-zinc-400 font-sans leading-tight">
                  {item.desc}
                </div>
              </button>
            ))}
          </div>
        </div>

        {/* Machine Selection */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div>
            <label className="block text-xs font-mono-tech text-zinc-400 uppercase tracking-wider mb-1.5">
              2. Target Asset / Machine
            </label>
            <select
              value={targetMachineId}
              onChange={(e) => {
                setTargetMachineId(e.target.value);
                const m = machines.find(item => item.id === e.target.value);
                if (m) {
                  setReportTitle(`Incident Investigation: ${m.name} (${m.tag}) Excursion`);
                }
              }}
              className="w-full bg-zinc-950 border border-zinc-700 rounded-lg p-2.5 text-xs font-mono-tech text-white focus:border-emerald-500 focus:outline-none"
            >
              {machines.map(m => (
                <option key={m.id} value={m.id}>
                  {m.tag} — {m.name} ({m.status.toUpperCase()})
                </option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-xs font-mono-tech text-zinc-400 uppercase tracking-wider mb-1.5">
              Certifying Lead Engineer
            </label>
            <input
              type="text"
              readOnly
              value={`${currentUser.name} (${currentUser.badgeId})`}
              className="w-full bg-zinc-950/60 border border-zinc-800 rounded-lg p-2.5 text-xs font-mono-tech text-zinc-400 cursor-not-allowed"
            />
          </div>
        </div>

        {/* Report Name */}
        <div>
          <label className="block text-xs font-mono-tech text-zinc-400 uppercase tracking-wider mb-1.5">
            3. Report Title
          </label>
          <input
            type="text"
            value={reportTitle}
            onChange={(e) => setReportTitle(e.target.value)}
            placeholder="Enter report document title..."
            className="w-full bg-zinc-950 border border-zinc-700 rounded-lg p-2.5 text-xs font-mono-tech text-white focus:border-emerald-500 focus:outline-none"
          />
        </div>

        {/* Operational Context Notes */}
        <div>
          <label className="block text-xs font-mono-tech text-zinc-400 uppercase tracking-wider mb-1.5">
            4. Executive Investigation Notes
          </label>
          <textarea
            rows={3}
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
            placeholder="Add specific shift notes or field technician observations..."
            className="w-full bg-zinc-950 border border-zinc-700 rounded-lg p-2.5 text-xs text-white focus:border-emerald-500 focus:outline-none font-sans"
          />
        </div>

        {/* Standards Notice */}
        <div className="p-3 rounded-lg bg-zinc-950 border border-zinc-800 text-[11px] font-mono-tech text-zinc-400 flex items-center justify-between">
          <span>Compliance Format: ISO 14224 • API 670 • IEC 62443</span>
          <span className="text-emerald-400 font-bold">DIGITAL AUDIT READY</span>
        </div>
      </form>
    </Modal>
  );
};
